analyzer:
  strong-mode: true
#    implicit-casts: false
#    implicit-dynamic: false
  exclude:
    - lib/src/json/*.dart
    - web/main.dart
  plugins:
    angular:
      enabled: true
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
